[package]
name = "scroll_format_app"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
futures.workspace = true
scroll_format_core = { path = "../core" }
scroll_format_infra = { path = "../infra" }
scroll_format_converters = { path = "../converters" }

[dev-dependencies]
image.workspace = true
